### ISSUE TITLE
default local scene

### ISSUE THREAD

**Issue by sirkitree** [scenevr/docs#2]
Not sure if this is a change needed to the docs or to the samples, but the [directions](http://docs.scenevr.com/getting-started.html) give a link to
`http://client.scenevr.com/?connect=localhost:8080/index.xml`

but you cannot connect to index.xml at this point because it doesn't exist within the sample-master that you download and run through the server.

Should we add back an index.xml file to the samples, or should we change this link in the docs to one of the other files (like welcome.xml)?

**Comment by sirkitree** [comment]
welcome is kinda weird, hello might be better

**Comment by bnolan** [comment]
Great thanks for this. I removed the index file when refactoring to make scenes load and unload dynamically, that PR is a good fix.

I created [this sexy issue](https://github.com/scenevr/server/issues/69) to re-add the index.xml.
